package io.swagger.v3.core.converting;

import io.swagger.v3.core.converter.ModelConverters;
import io.swagger.v3.core.oas.models.RootShared;
import io.swagger.v3.core.oas.models.RootUnique;
import org.testng.annotations.Test;

import static org.testng.AssertJUnit.assertTrue;

/**
 * Reproduces a resolution-time blowup that is structurally distinct from
 * https://github.com/swagger-api/swagger-core/issues/5091 (fixed by PR #5114).
 *
 * That issue/fix was scoped to the {@code @ArraySchema(schema = @Schema(implementation = ...))}
 * annotation-driven path, where {@code AnnotationsUtils} helpers were reinstantiating a brand
 * new {@code ModelConverterContextImpl} and losing the whole cache.
 *
 * This test targets the *plain* Jackson bean-introspection path (no {@code @Schema}/
 * {@code @ArraySchema} annotations at all — the situation for third-party interfaces an
 * application doesn't control, e.g. the javax/jakarta JCR API: {@code Node}, {@code NodeType},
 * {@code NodeTypeManager}, {@code Session}, {@code Workspace}, ... are all returned by many
 * differently-named getters scattered across many other JCR interfaces).
 *
 * Root cause: {@link io.swagger.v3.core.converter.AnnotatedType#equals} includes
 * {@code propertyName} in its equality/hash whenever {@code schemaProperty} is true. Since
 * {@code propertyName} is the name of the *declaring* getter (e.g. "primaryNodeType" on
 * {@code Node}, "getAllNodeTypes" on {@code NodeTypeManager}), the exact same target class,
 * reached via two differently-named getters (even from different parent classes), is treated
 * as two distinct cache entries in {@code ModelConverterContextImpl.processedTypes}/{@code
 * modelByType}. Each distinct entry re-triggers a *full* re-walk of that target class's own
 * properties (see {@code ModelResolver.resolve()} -> {@code resolveSchemaMembers}), which
 * recurses the same way into whatever that class references. For a densely
 * interconnected API (the same handful of classes reachable via many differently-named
 * getters, several levels deep) this makes the number of *effective* resolutions grow
 * combinatorially with depth, even though the number of classes involved is small.
 *
 * {@link RootUnique} and {@link RootShared} (generated by
 * {@code src/test/resources/scripts/gen_jcr_diamond.py}, fan-out F=60, 3 hops) have IDENTICAL topology:
 * a small "diamond" DAG where the same F leaf/L2 classes are reachable from many parents.
 * The only difference is naming:
 * <ul>
 *   <li>{@code RootUnique}'s graph names every edge into a given target uniquely per edge
 *   (as naturally happens with unrelated getters on a real, uncontrolled API) -&gt; triggers
 *   the bug -&gt; ~1 + F + F^2 + F^3 effective resolutions.</li>
 *   <li>{@code RootShared}'s graph uses one canonical getter name per target regardless of
 *   which parent declares it -&gt; every reference to a given target is a cache hit after the
 *   first -&gt; ~1 + 4F effective resolutions.</li>
 * </ul>
 * Both graphs describe the exact same number of classes and the exact same shape of API
 * surface; only whether callers happen to reuse getter names differs — something an
 * application has no control over when the classes come from a third-party library.
 */
public class JcrLikeDiamondResolutionTimingTest {

    @Test
    public void uniquelyNamedDiamondIsNotDisproportionatelySlowerThanSharedNamedDiamond() {
        final long sharedMs = measureTiming(3, () ->
                ModelConverters.getInstance(true).readAllAsResolvedSchema(RootShared.class));
        System.out.println("Shared-name diamond (control) duration: " + sharedMs + "ms");

        final long uniqueMs = measureTiming(1, () ->
                ModelConverters.getInstance(true).readAllAsResolvedSchema(RootUnique.class));
        System.out.println("Unique-name diamond (bug case) duration: " + uniqueMs + "ms");

        final float factor = (float) uniqueMs / Math.max(sharedMs, 1);
        System.out.println("Factor: " + factor);

        // Both graphs have identical topology (same class count, same fan-out, same depth).
        // The only difference is whether getters into a shared target reuse a name or not -
        // something callers of a third-party API (like the JCR interfaces) don't control.
        // A healthy resolver should treat these near-identically; a resolver that fragments
        // its cache by declaring-property-name will blow up combinatorially with depth here.
        assertTrue("Resolving the uniquely-named diamond took " + factor
                        + "x longer than the identically-shaped, shared-name diamond ("
                        + uniqueMs + "ms vs " + sharedMs + "ms) - the resolver is not reusing "
                        + "cached schemas across differently-named references to the same type.",
                factor <= 5);
    }

    private long measureTiming(int iterations, Runnable runnable) {
        final long start = System.currentTimeMillis();
        for (int i = 0; i < iterations; i++) {
            runnable.run();
        }
        final long end = System.currentTimeMillis();
        return (end - start) / iterations;
    }
}
