//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.18 at 10:36:31 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.openapis.org/test/nested", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.swagger.v3.core.oas.models.xmltest;
