// * * * * * * * * * * * *
// Plugins
// * * * * * * * * * * * *
plugins {
    id 'java-gradle-plugin'
    // Publishing publicly
    id 'com.gradle.plugin-publish' version '2.1.1'
    // Publishing to maven
    id 'maven-publish'
}

// * * * * * * * * * * * *
// Dependencies
// * * * * * * * * * * * *

import org.apache.tools.ant.filters.ReplaceTokens

repositories {
    mavenLocal()
    mavenCentral()
}

processResources {
    filter(ReplaceTokens, tokens: [
        "project.version": project.version
    ])
}

compileJava {
    options.release = 17
}

dependencies {
    implementation gradleApi()

    testImplementation gradleTestKit()
    testImplementation 'org.wiremock:wiremock:4.0.0-beta.36'
    testImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'
    testImplementation 'com.google.guava:guava:32.1.3-jre'
    testImplementation 'jakarta.ws.rs:jakarta.ws.rs-api:4.0.0'
    testImplementation "io.github.vpelikh:swagger-jakarta-rest:${project.version}"
    testImplementation 'org.testng:testng:7.10.2'
    testImplementation "org.apache.httpcomponents:httpclient:4.5.14"
    testImplementation "commons-codec:commons-codec:1.16.0"
    testImplementation "commons-io:commons-io:2.15.1"
    testImplementation "org.apache.commons:commons-compress:1.25.0"
    testImplementation "com.github.jknack:handlebars:4.3.1"
    testImplementation "com.github.jknack:handlebars-helpers:4.3.1"
}

// * * * * * * * * * * * *
// Project configuration
// * * * * * * * * * * * *

project.description     = 'Gradle Plugin for Swagger core'
project.group           = 'io.github.vpelikh'

project.ext.name        = 'swagger-gradle-plugin'
project.ext.pluginId    = 'io.github.vpelikh.swagger-gradle-plugin'
project.ext.scm         = 'https://github.com/vpelikh/swagger-core.git'
project.ext.url         = 'https://github.com/vpelikh/swagger-core/tree/master/modules/swagger-gradle-plugin'

// Configuration for: java-gradle-plugin
gradlePlugin {
    plugins {
        swagger {
            id = project.pluginId
            implementationClass = 'io.swagger.v3.plugins.gradle.SwaggerPlugin'
        }
    }
}

// * * * * * * * * * * * *
// Publishing
// * * * * * * * * * * * *

// Publishing to plugins.gradle.org
// --------------------------------

// Configuration for: com.gradle.plugin-publish
gradlePlugin {
    website = project.url
    vcsUrl = project.scm

    plugins {
        swagger {
            id = project.pluginId
            displayName = 'Swagger Gradle Plugin'
            description = project.description
            implementationClass = 'io.swagger.v3.plugins.gradle.SwaggerPlugin'
            tags = ['swagger', 'openapi', 'api']
        }
    }
}

test {
    useTestNG()
}

publishing {
    repositories {
        maven {
            url mavenLocal().url
        }
    }
}
