/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.models.parameters.Parameter;
import io.swagger.models.servers.Server;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PathItem
 *
 * @link https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#pathItemObject
 */

public class PathItem {
  @JsonProperty("$ref")
  private String ref = null;
  @JsonProperty("summary")
  private String summary = null;
  @JsonProperty("description")
  private String description = null;
  @JsonProperty("get")
  private Operation get = null;
  @JsonProperty("put")
  private Operation put = null;
  @JsonProperty("post")
  private Operation post = null;
  @JsonProperty("delete")
  private Operation delete = null;
  @JsonProperty("options")
  private Operation options = null;
  @JsonProperty("head")
  private Operation head = null;
  @JsonProperty("patch")
  private Operation patch = null;
  @JsonProperty("trace")
  private Operation trace = null;
  @JsonProperty("servers")
  private List<Server> servers = null;
  @JsonProperty("parameters")
  private List<Parameter> parameters = null;
  private java.util.Map<String, Object> extensions = null;

  /**
   * returns the ref property from a PathItem instance.
   *
   * @return String ref
   **/
  @ApiModelProperty(value = "")
  public String getRef() {
    return ref;
  }

  public void setRef(String ref) {
    this.ref = ref;
  }

  public PathItem ref(String ref) {
    this.ref = ref;
    return this;
  }

  /**
   * returns the summary property from a PathItem instance.
   *
   * @return String summary
   **/
  @ApiModelProperty(value = "")
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public PathItem summary(String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * returns the description property from a PathItem instance.
   *
   * @return String description
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PathItem description(String description) {
    this.description = description;
    return this;
  }

  /**
   * returns the get property from a PathItem instance.
   *
   * @return Operation get
   **/
  @ApiModelProperty(value = "")
  public Operation getGet() {
    return get;
  }

  public void setGet(Operation get) {
    this.get = get;
  }

  public PathItem get(Operation get) {
    this.get = get;
    return this;
  }

  /**
   * returns the put property from a PathItem instance.
   *
   * @return Operation put
   **/
  @ApiModelProperty(value = "")
  public Operation getPut() {
    return put;
  }

  public void setPut(Operation put) {
    this.put = put;
  }

  public PathItem put(Operation put) {
    this.put = put;
    return this;
  }

  /**
   * returns the post property from a PathItem instance.
   *
   * @return Operation post
   **/
  @ApiModelProperty(value = "")
  public Operation getPost() {
    return post;
  }

  public void setPost(Operation post) {
    this.post = post;
  }

  public PathItem post(Operation post) {
    this.post = post;
    return this;
  }

  /**
   * returns the delete property from a PathItem instance.
   *
   * @return Operation delete
   **/
  @ApiModelProperty(value = "")
  public Operation getDelete() {
    return delete;
  }

  public void setDelete(Operation delete) {
    this.delete = delete;
  }

  public PathItem delete(Operation delete) {
    this.delete = delete;
    return this;
  }

  /**
   * returns the options property from a PathItem instance.
   *
   * @return Operation options
   **/
  @ApiModelProperty(value = "")
  public Operation getOptions() {
    return options;
  }

  public void setOptions(Operation options) {
    this.options = options;
  }

  public PathItem options(Operation options) {
    this.options = options;
    return this;
  }

  /**
   * returns the head property from a PathItem instance.
   *
   * @return Operation head
   **/
  @ApiModelProperty(value = "")
  public Operation getHead() {
    return head;
  }

  public void setHead(Operation head) {
    this.head = head;
  }

  public PathItem head(Operation head) {
    this.head = head;
    return this;
  }

  /**
   * returns the patch property from a PathItem instance.
   *
   * @return Operation patch
   **/
  @ApiModelProperty(value = "")
  public Operation getPatch() {
    return patch;
  }

  public void setPatch(Operation patch) {
    this.patch = patch;
  }

  public PathItem patch(Operation patch) {
    this.patch = patch;
    return this;
  }

  /**
   * returns the trace property from a PathItem instance.
   *
   * @return Operation trace
   **/
  @ApiModelProperty(value = "")
  public Operation getTrace() {
    return trace;
  }

  public void setTrace(Operation trace) {
    this.trace = trace;
  }

  public PathItem trace(Operation trace) {
    this.trace = trace;
    return this;
  }

  /**
   * returns the servers property from a PathItem instance.
   *
   * @return List<Server> servers
   **/
  @ApiModelProperty(value = "")
  public List<Server> getServers() {
    return servers;
  }

  public void setServers(List<Server> servers) {
    this.servers = servers;
  }

  public PathItem servers(List<Server> servers) {
    this.servers = servers;
    return this;
  }

  public PathItem addServersItem(Server serversItem) {
    if(this.servers == null) {
      this.servers = new ArrayList<Server>();
    }
    this.servers.add(serversItem);
    return this;
  }

  /**
   * returns the parameters property from a PathItem instance.
   *
   * @return List<Parameter> parameters
   **/
  @ApiModelProperty(value = "")
  public List<Parameter> getParameters() {
    return parameters;
  }

  public void setParameters(List<Parameter> parameters) {
    this.parameters = parameters;
  }

  public PathItem parameters(List<Parameter> parameters) {
    this.parameters = parameters;
    return this;
  }

  public PathItem addParametersItem(Parameter parametersItem) {
    if(this.parameters == null) {
      this.parameters = new ArrayList<Parameter>();
    }
    this.parameters.add(parametersItem);
    return this;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PathItem pathItem = (PathItem) o;
    return Objects.equals(this.ref, pathItem.ref) &&
        Objects.equals(this.summary, pathItem.summary) &&
        Objects.equals(this.description, pathItem.description) &&
        Objects.equals(this.get, pathItem.get) &&
        Objects.equals(this.put, pathItem.put) &&
        Objects.equals(this.post, pathItem.post) &&
        Objects.equals(this.delete, pathItem.delete) &&
        Objects.equals(this.options, pathItem.options) &&
        Objects.equals(this.head, pathItem.head) &&
        Objects.equals(this.patch, pathItem.patch) &&
        Objects.equals(this.trace, pathItem.trace) &&
        Objects.equals(this.servers, pathItem.servers) &&
        Objects.equals(this.parameters, pathItem.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ref, summary, description, get, put, post, delete, options, head, patch, trace, servers, parameters);
  }


  public java.util.Map<String, Object> getExtensions() {
    return extensions;
  }

  public void addExtension(String name, Object value) {
    if(this.extensions == null) {
      this.extensions = new java.util.HashMap<>();
    }
    this.extensions.put(name, value);
  }

  public void setExtensions(java.util.Map<String, Object> extensions) {
    this.extensions = extensions;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PathItem {\n");
    
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    get: ").append(toIndentedString(get)).append("\n");
    sb.append("    put: ").append(toIndentedString(put)).append("\n");
    sb.append("    post: ").append(toIndentedString(post)).append("\n");
    sb.append("    delete: ").append(toIndentedString(delete)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    head: ").append(toIndentedString(head)).append("\n");
    sb.append("    patch: ").append(toIndentedString(patch)).append("\n");
    sb.append("    trace: ").append(toIndentedString(trace)).append("\n");
    sb.append("    servers: ").append(toIndentedString(servers)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

