/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.models.security;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OAuthFlows
 *
 * @link https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#oauthFlowsObject
 */

public class OAuthFlows {
  @JsonProperty("implicit")
  private OAuthFlow implicit = null;
  @JsonProperty("password")
  private OAuthFlow password = null;
  @JsonProperty("clientCredentials")
  private OAuthFlow clientCredentials = null;
  @JsonProperty("authorizationCode")
  private OAuthFlow authorizationCode = null;
  private java.util.Map<String, Object> extensions = null;

  /**
   * returns the implicit property from a OAuthFlows instance.
   *
   * @return OAuthFlow implicit
   **/
  @ApiModelProperty(value = "")
  public OAuthFlow getImplicit() {
    return implicit;
  }

  public void setImplicit(OAuthFlow implicit) {
    this.implicit = implicit;
  }

  public OAuthFlows implicit(OAuthFlow implicit) {
    this.implicit = implicit;
    return this;
  }

  /**
   * returns the password property from a OAuthFlows instance.
   *
   * @return OAuthFlow password
   **/
  @ApiModelProperty(value = "")
  public OAuthFlow getPassword() {
    return password;
  }

  public void setPassword(OAuthFlow password) {
    this.password = password;
  }

  public OAuthFlows password(OAuthFlow password) {
    this.password = password;
    return this;
  }

  /**
   * returns the clientCredentials property from a OAuthFlows instance.
   *
   * @return OAuthFlow clientCredentials
   **/
  @ApiModelProperty(value = "")
  public OAuthFlow getClientCredentials() {
    return clientCredentials;
  }

  public void setClientCredentials(OAuthFlow clientCredentials) {
    this.clientCredentials = clientCredentials;
  }

  public OAuthFlows clientCredentials(OAuthFlow clientCredentials) {
    this.clientCredentials = clientCredentials;
    return this;
  }

  /**
   * returns the authorizationCode property from a OAuthFlows instance.
   *
   * @return OAuthFlow authorizationCode
   **/
  @ApiModelProperty(value = "")
  public OAuthFlow getAuthorizationCode() {
    return authorizationCode;
  }

  public void setAuthorizationCode(OAuthFlow authorizationCode) {
    this.authorizationCode = authorizationCode;
  }

  public OAuthFlows authorizationCode(OAuthFlow authorizationCode) {
    this.authorizationCode = authorizationCode;
    return this;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OAuthFlows oauthFlows = (OAuthFlows) o;
    return Objects.equals(this.implicit, oauthFlows.implicit) &&
        Objects.equals(this.password, oauthFlows.password) &&
        Objects.equals(this.clientCredentials, oauthFlows.clientCredentials) &&
        Objects.equals(this.authorizationCode, oauthFlows.authorizationCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(implicit, password, clientCredentials, authorizationCode);
  }


  public java.util.Map<String, Object> getExtensions() {
    return extensions;
  }

  public void addExtension(String name, Object value) {
    if(this.extensions == null) {
      this.extensions = new java.util.HashMap<>();
    }
    this.extensions.put(name, value);
  }

  public void setExtensions(java.util.Map<String, Object> extensions) {
    this.extensions = extensions;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuthFlows {\n");
    
    sb.append("    implicit: ").append(toIndentedString(implicit)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    clientCredentials: ").append(toIndentedString(clientCredentials)).append("\n");
    sb.append("    authorizationCode: ").append(toIndentedString(authorizationCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

