/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.models.parameters;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.models.examples.Example;
import io.swagger.models.media.Content;
import io.swagger.models.media.Schema;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PathParameter
 */

public class PathParameter extends Parameter {
  @JsonProperty("in")
  private String in = "path";

  /**
   * returns the in property from a PathParameter instance.
   *
   * @return String in
   **/
  @ApiModelProperty(value = "")
  public String getIn() {
    return in;
  }

  public void setIn(String in) {
    this.in = in;
  }

  public PathParameter in(String in) {
    this.in = in;
    return this;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PathParameter pathParameter = (PathParameter) o;
    return Objects.equals(this.in, pathParameter.in) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(in, super.hashCode());
  }



  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PathParameter {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    in: ").append(toIndentedString(in)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

