name: 'Check BOM version'
description: 'Verify swagger-bom version matches root POM version'
runs:
  using: "composite"
  steps:
    - run: |
        ROOT_VERSION=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
        BOM_VERSION=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec --file modules/swagger-bom/pom.xml)
        if [ "${ROOT_VERSION}" != "${BOM_VERSION}" ]; then
          echo "ERROR: swagger-bom version mismatch"
          exit 1
        fi
      shell: bash