name: 'Check BOM version'
description: 'Verify swagger-bom version matches root POM version'
runs:
  using: "composite"
  steps:
    - run: |
        ROOT_VERSION=$(./mvnw -q -DforceStdout help:evaluate -Dexpression=project.version --non-recursive)
        BOM_VERSION=$(./mvnw -q -DforceStdout help:evaluate -Dexpression=project.version --non-recursive --file modules/swagger-bom/pom.xml)
        if [ "${ROOT_VERSION}" != "${BOM_VERSION}" ]; then
          echo "ERROR: swagger-bom version mismatch"
          exit 1
        fi
      shell: bash