/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.models.media;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * EncodingProperty
 *
 * @link https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#encodingPropertyObject
 */

public class EncodingProperty {
  @JsonProperty("contentType")
  private String contentType = null;
  @JsonProperty("headers")
  private Object headers = null;
  /**
   * Gets or Sets style
   */
  public enum StyleEnum {
    FORM("form"),
    
    SPACEDELIMITED("spaceDelimited"),
    
    PIPEDELIMITED("pipeDelimited"),
    
    DEEPOBJECT("deepObject");

    private String value;

    StyleEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StyleEnum fromValue(String text) {
      for (StyleEnum b : StyleEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("style")
  private StyleEnum style = null;
  @JsonProperty("explode")
  private Boolean explode = null;
  private java.util.Map<String, Object> extensions = null;

  /**
   * returns the contentType property from a EncodingProperty instance.
   *
   * @return String contentType
   **/
  @ApiModelProperty(value = "")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public EncodingProperty contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

  /**
   * returns the headers property from a EncodingProperty instance.
   *
   * @return Object headers
   **/
  @ApiModelProperty(value = "")
  public Object getHeaders() {
    return headers;
  }

  public void setHeaders(Object headers) {
    this.headers = headers;
  }

  public EncodingProperty headers(Object headers) {
    this.headers = headers;
    return this;
  }

  /**
   * returns the style property from a EncodingProperty instance.
   *
   * @return StyleEnum style
   **/
  @ApiModelProperty(value = "")
  public StyleEnum getStyle() {
    return style;
  }

  public void setStyle(StyleEnum style) {
    this.style = style;
  }

  public EncodingProperty style(StyleEnum style) {
    this.style = style;
    return this;
  }

  /**
   * returns the explode property from a EncodingProperty instance.
   *
   * @return Boolean explode
   **/
  @ApiModelProperty(value = "")
  public Boolean getExplode() {
    return explode;
  }

  public void setExplode(Boolean explode) {
    this.explode = explode;
  }

  public EncodingProperty explode(Boolean explode) {
    this.explode = explode;
    return this;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EncodingProperty encodingProperty = (EncodingProperty) o;
    return Objects.equals(this.contentType, encodingProperty.contentType) &&
        Objects.equals(this.headers, encodingProperty.headers) &&
        Objects.equals(this.style, encodingProperty.style) &&
        Objects.equals(this.explode, encodingProperty.explode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentType, headers, style, explode);
  }


  public java.util.Map<String, Object> getExtensions() {
    return extensions;
  }

  public void addExtension(String name, Object value) {
    if(this.extensions == null) {
      this.extensions = new java.util.HashMap<>();
    }
    this.extensions.put(name, value);
  }

  public void setExtensions(java.util.Map<String, Object> extensions) {
    this.extensions = extensions;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EncodingProperty {\n");
    
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("    explode: ").append(toIndentedString(explode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

