/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.models.media;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.models.examples.Example;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MediaType
 *
 * @link https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#mediaTypeObject
 */

public class MediaType {
  @JsonProperty("schema")
  private Schema schema = null;
  @JsonProperty("examples")
  private List<Example> examples = null;
  @JsonProperty("example")
  private Example example = null;
  @JsonProperty("Encoding")
  private Encoding encoding = null;
  private java.util.Map<String, Object> extensions = null;

  /**
   * returns the schema property from a MediaType instance.
   *
   * @return Schema schema
   **/
  @ApiModelProperty(value = "")
  public Schema getSchema() {
    return schema;
  }

  public void setSchema(Schema schema) {
    this.schema = schema;
  }

  public MediaType schema(Schema schema) {
    this.schema = schema;
    return this;
  }

  /**
   * returns the examples property from a MediaType instance.
   *
   * @return List<Example> examples
   **/
  @ApiModelProperty(value = "")
  public List<Example> getExamples() {
    return examples;
  }

  public void setExamples(List<Example> examples) {
    this.examples = examples;
  }

  public MediaType examples(List<Example> examples) {
    this.examples = examples;
    return this;
  }

  public MediaType addExamplesItem(Example examplesItem) {
    if(this.examples == null) {
      this.examples = new ArrayList<Example>();
    }
    this.examples.add(examplesItem);
    return this;
  }

  /**
   * returns the example property from a MediaType instance.
   *
   * @return Example example
   **/
  @ApiModelProperty(value = "")
  public Example getExample() {
    return example;
  }

  public void setExample(Example example) {
    this.example = example;
  }

  public MediaType example(Example example) {
    this.example = example;
    return this;
  }

  /**
   * returns the encoding property from a MediaType instance.
   *
   * @return Encoding encoding
   **/
  @ApiModelProperty(value = "")
  public Encoding getEncoding() {
    return encoding;
  }

  public void setEncoding(Encoding encoding) {
    this.encoding = encoding;
  }

  public MediaType encoding(Encoding encoding) {
    this.encoding = encoding;
    return this;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MediaType mediaType = (MediaType) o;
    return Objects.equals(this.schema, mediaType.schema) &&
        Objects.equals(this.examples, mediaType.examples) &&
        Objects.equals(this.example, mediaType.example) &&
        Objects.equals(this.encoding, mediaType.encoding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schema, examples, example, encoding);
  }


  public java.util.Map<String, Object> getExtensions() {
    return extensions;
  }

  public void addExtension(String name, Object value) {
    if(this.extensions == null) {
      this.extensions = new java.util.HashMap<>();
    }
    this.extensions.put(name, value);
  }

  public void setExtensions(java.util.Map<String, Object> extensions) {
    this.extensions = extensions;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediaType {\n");
    
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    examples: ").append(toIndentedString(examples)).append("\n");
    sb.append("    example: ").append(toIndentedString(example)).append("\n");
    sb.append("    encoding: ").append(toIndentedString(encoding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

