/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.models.media;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.models.ExternalDocumentation;
import io.swagger.models.examples.Example;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OneOfSchema
 */

public class OneOfSchema extends Schema {
  @JsonProperty("anyOf")
  private List<Schema> anyOf = null;

  /**
   * returns the anyOf property from a OneOfSchema instance.
   *
   * @return List<Schema> anyOf
   **/
  @ApiModelProperty(value = "")
  public List<Schema> getAnyOf() {
    return anyOf;
  }

  public void setAnyOf(List<Schema> anyOf) {
    this.anyOf = anyOf;
  }

  public OneOfSchema anyOf(List<Schema> anyOf) {
    this.anyOf = anyOf;
    return this;
  }

  public OneOfSchema addAnyOfItem(Schema anyOfItem) {
    if(this.anyOf == null) {
      this.anyOf = new ArrayList<Schema>();
    }
    this.anyOf.add(anyOfItem);
    return this;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OneOfSchema oneOfSchema = (OneOfSchema) o;
    return Objects.equals(this.anyOf, oneOfSchema.anyOf) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anyOf, super.hashCode());
  }



  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OneOfSchema {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    anyOf: ").append(toIndentedString(anyOf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

