/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.models.media;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.models.ExternalDocumentation;
import io.swagger.models.examples.Example;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Schema
 *
 * @link https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#schemaObject
 */

public class Schema {
  @JsonProperty("title")
  private String title = null;
  @JsonProperty("multipleOf")
  private BigDecimal multipleOf = null;
  @JsonProperty("maximum")
  private BigDecimal maximum = null;
  @JsonProperty("exclusiveMaximum")
  private Boolean exclusiveMaximum = null;
  @JsonProperty("minimum")
  private BigDecimal minimum = null;
  @JsonProperty("exclusiveMinimum")
  private Boolean exclusiveMinimum = null;
  @JsonProperty("maxLength")
  private Integer maxLength = null;
  @JsonProperty("minLength")
  private Integer minLength = null;
  @JsonProperty("pattern")
  private String pattern = null;
  @JsonProperty("maxItems")
  private Integer maxItems = null;
  @JsonProperty("minItems")
  private Integer minItems = null;
  @JsonProperty("uniqueItems")
  private Boolean uniqueItems = null;
  @JsonProperty("maxProperties")
  private Integer maxProperties = null;
  @JsonProperty("minProperties")
  private Integer minProperties = null;
  @JsonProperty("required")
  private List<String> required = null;
  @JsonProperty("enum")
  private List<Object> _enum = null;
  @JsonProperty("type")
  private String type = null;
  @JsonProperty("not")
  private Schema not = null;
  @JsonProperty("properties")
  private Map<String, Schema> properties = null;
  @JsonProperty("additionalProperties")
  private Schema additionalProperties = null;
  @JsonProperty("description")
  private String description = null;
  @JsonProperty("format")
  private String format = null;
  @JsonProperty("$ref")
  private String ref = null;
  @JsonProperty("nulable")
  private Boolean nulable = null;
  @JsonProperty("readOnly")
  private Boolean readOnly = null;
  @JsonProperty("writeOnly")
  private Boolean writeOnly = null;
  @JsonProperty("examples")
  private List<Example> examples = null;
  @JsonProperty("example")
  private Example example = null;
  @JsonProperty("externalDocs")
  private ExternalDocumentation externalDocs = null;
  @JsonProperty("deprecated")
  private Boolean deprecated = null;
  @JsonProperty("xml")
  private XML xml = null;
  private java.util.Map<String, Object> extensions = null;

  /**
   * returns the title property from a Schema instance.
   *
   * @return String title
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Schema title(String title) {
    this.title = title;
    return this;
  }

  /**
   * returns the multipleOf property from a Schema instance.
   *
   * minimum: 0
   * @return BigDecimal multipleOf
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getMultipleOf() {
    return multipleOf;
  }

  public void setMultipleOf(BigDecimal multipleOf) {
    this.multipleOf = multipleOf;
  }

  public Schema multipleOf(BigDecimal multipleOf) {
    this.multipleOf = multipleOf;
    return this;
  }

  /**
   * returns the maximum property from a Schema instance.
   *
   * @return BigDecimal maximum
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getMaximum() {
    return maximum;
  }

  public void setMaximum(BigDecimal maximum) {
    this.maximum = maximum;
  }

  public Schema maximum(BigDecimal maximum) {
    this.maximum = maximum;
    return this;
  }

  /**
   * returns the exclusiveMaximum property from a Schema instance.
   *
   * @return Boolean exclusiveMaximum
   **/
  @ApiModelProperty(value = "")
  public Boolean getExclusiveMaximum() {
    return exclusiveMaximum;
  }

  public void setExclusiveMaximum(Boolean exclusiveMaximum) {
    this.exclusiveMaximum = exclusiveMaximum;
  }

  public Schema exclusiveMaximum(Boolean exclusiveMaximum) {
    this.exclusiveMaximum = exclusiveMaximum;
    return this;
  }

  /**
   * returns the minimum property from a Schema instance.
   *
   * @return BigDecimal minimum
   **/
  @ApiModelProperty(value = "")
  public BigDecimal getMinimum() {
    return minimum;
  }

  public void setMinimum(BigDecimal minimum) {
    this.minimum = minimum;
  }

  public Schema minimum(BigDecimal minimum) {
    this.minimum = minimum;
    return this;
  }

  /**
   * returns the exclusiveMinimum property from a Schema instance.
   *
   * @return Boolean exclusiveMinimum
   **/
  @ApiModelProperty(value = "")
  public Boolean getExclusiveMinimum() {
    return exclusiveMinimum;
  }

  public void setExclusiveMinimum(Boolean exclusiveMinimum) {
    this.exclusiveMinimum = exclusiveMinimum;
  }

  public Schema exclusiveMinimum(Boolean exclusiveMinimum) {
    this.exclusiveMinimum = exclusiveMinimum;
    return this;
  }

  /**
   * returns the maxLength property from a Schema instance.
   *
   * minimum: 0
   * @return Integer maxLength
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxLength() {
    return maxLength;
  }

  public void setMaxLength(Integer maxLength) {
    this.maxLength = maxLength;
  }

  public Schema maxLength(Integer maxLength) {
    this.maxLength = maxLength;
    return this;
  }

  /**
   * returns the minLength property from a Schema instance.
   *
   * minimum: 0
   * @return Integer minLength
   **/
  @ApiModelProperty(value = "")
  public Integer getMinLength() {
    return minLength;
  }

  public void setMinLength(Integer minLength) {
    this.minLength = minLength;
  }

  public Schema minLength(Integer minLength) {
    this.minLength = minLength;
    return this;
  }

  /**
   * returns the pattern property from a Schema instance.
   *
   * @return String pattern
   **/
  @ApiModelProperty(value = "")
  public String getPattern() {
    return pattern;
  }

  public void setPattern(String pattern) {
    this.pattern = pattern;
  }

  public Schema pattern(String pattern) {
    this.pattern = pattern;
    return this;
  }

  /**
   * returns the maxItems property from a Schema instance.
   *
   * minimum: 0
   * @return Integer maxItems
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxItems() {
    return maxItems;
  }

  public void setMaxItems(Integer maxItems) {
    this.maxItems = maxItems;
  }

  public Schema maxItems(Integer maxItems) {
    this.maxItems = maxItems;
    return this;
  }

  /**
   * returns the minItems property from a Schema instance.
   *
   * minimum: 0
   * @return Integer minItems
   **/
  @ApiModelProperty(value = "")
  public Integer getMinItems() {
    return minItems;
  }

  public void setMinItems(Integer minItems) {
    this.minItems = minItems;
  }

  public Schema minItems(Integer minItems) {
    this.minItems = minItems;
    return this;
  }

  /**
   * returns the uniqueItems property from a Schema instance.
   *
   * @return Boolean uniqueItems
   **/
  @ApiModelProperty(value = "")
  public Boolean getUniqueItems() {
    return uniqueItems;
  }

  public void setUniqueItems(Boolean uniqueItems) {
    this.uniqueItems = uniqueItems;
  }

  public Schema uniqueItems(Boolean uniqueItems) {
    this.uniqueItems = uniqueItems;
    return this;
  }

  /**
   * returns the maxProperties property from a Schema instance.
   *
   * minimum: 0
   * @return Integer maxProperties
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxProperties() {
    return maxProperties;
  }

  public void setMaxProperties(Integer maxProperties) {
    this.maxProperties = maxProperties;
  }

  public Schema maxProperties(Integer maxProperties) {
    this.maxProperties = maxProperties;
    return this;
  }

  /**
   * returns the minProperties property from a Schema instance.
   *
   * minimum: 0
   * @return Integer minProperties
   **/
  @ApiModelProperty(value = "")
  public Integer getMinProperties() {
    return minProperties;
  }

  public void setMinProperties(Integer minProperties) {
    this.minProperties = minProperties;
  }

  public Schema minProperties(Integer minProperties) {
    this.minProperties = minProperties;
    return this;
  }

  /**
   * returns the required property from a Schema instance.
   *
   * @return List<String> required
   **/
  @ApiModelProperty(value = "")
  public List<String> getRequired() {
    return required;
  }

  public void setRequired(List<String> required) {
    this.required = required;
  }

  public Schema required(List<String> required) {
    this.required = required;
    return this;
  }

  public Schema addRequiredItem(String requiredItem) {
    if(this.required == null) {
      this.required = new ArrayList<String>();
    }
    this.required.add(requiredItem);
    return this;
  }

  /**
   * returns the _enum property from a Schema instance.
   *
   * @return List<Object> _enum
   **/
  @ApiModelProperty(value = "")
  public List<Object> getEnum() {
    return _enum;
  }

  public void setEnum(List<Object> _enum) {
    this._enum = _enum;
  }

  public Schema _enum(List<Object> _enum) {
    this._enum = _enum;
    return this;
  }

  public Schema addEnumItem(Object _enumItem) {
    if(this._enum == null) {
      this._enum = new ArrayList<Object>();
    }
    this._enum.add(_enumItem);
    return this;
  }

  /**
   * returns the type property from a Schema instance.
   *
   * @return String type
   **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Schema type(String type) {
    this.type = type;
    return this;
  }

  /**
   * returns the not property from a Schema instance.
   *
   * @return Schema not
   **/
  @ApiModelProperty(value = "")
  public Schema getNot() {
    return not;
  }

  public void setNot(Schema not) {
    this.not = not;
  }

  public Schema not(Schema not) {
    this.not = not;
    return this;
  }

  /**
   * returns the properties property from a Schema instance.
   *
   * @return Map<String, Schema> properties
   **/
  @ApiModelProperty(value = "")
  public Map<String, Schema> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, Schema> properties) {
    this.properties = properties;
  }

  public Schema properties(Map<String, Schema> properties) {
    this.properties = properties;
    return this;
  }

  public Schema addProperties(String key, Schema propertiesItem) {
    if(this.properties == null) {
      this.properties = new HashMap<String, Schema>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

  /**
   * returns the additionalProperties property from a Schema instance.
   *
   * @return Schema additionalProperties
   **/
  @ApiModelProperty(value = "")
  public Schema getAdditionalProperties() {
    return additionalProperties;
  }

  public void setAdditionalProperties(Schema additionalProperties) {
    this.additionalProperties = additionalProperties;
  }

  public Schema additionalProperties(Schema additionalProperties) {
    this.additionalProperties = additionalProperties;
    return this;
  }

  /**
   * returns the description property from a Schema instance.
   *
   * @return String description
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Schema description(String description) {
    this.description = description;
    return this;
  }

  /**
   * returns the format property from a Schema instance.
   *
   * @return String format
   **/
  @ApiModelProperty(value = "")
  public String getFormat() {
    return format;
  }

  public void setFormat(String format) {
    this.format = format;
  }

  public Schema format(String format) {
    this.format = format;
    return this;
  }

  /**
   * returns the ref property from a Schema instance.
   *
   * @return String ref
   **/
  @ApiModelProperty(value = "")
  public String getRef() {
    return ref;
  }

  public void setRef(String ref) {
    this.ref = ref;
  }

  public Schema ref(String ref) {
    this.ref = ref;
    return this;
  }

  /**
   * returns the nulable property from a Schema instance.
   *
   * @return Boolean nulable
   **/
  @ApiModelProperty(value = "")
  public Boolean getNulable() {
    return nulable;
  }

  public void setNulable(Boolean nulable) {
    this.nulable = nulable;
  }

  public Schema nulable(Boolean nulable) {
    this.nulable = nulable;
    return this;
  }

  /**
   * returns the readOnly property from a Schema instance.
   *
   * @return Boolean readOnly
   **/
  @ApiModelProperty(value = "")
  public Boolean getReadOnly() {
    return readOnly;
  }

  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }

  public Schema readOnly(Boolean readOnly) {
    this.readOnly = readOnly;
    return this;
  }

  /**
   * returns the writeOnly property from a Schema instance.
   *
   * @return Boolean writeOnly
   **/
  @ApiModelProperty(value = "")
  public Boolean getWriteOnly() {
    return writeOnly;
  }

  public void setWriteOnly(Boolean writeOnly) {
    this.writeOnly = writeOnly;
  }

  public Schema writeOnly(Boolean writeOnly) {
    this.writeOnly = writeOnly;
    return this;
  }

  /**
   * returns the examples property from a Schema instance.
   *
   * @return List<Example> examples
   **/
  @ApiModelProperty(value = "")
  public List<Example> getExamples() {
    return examples;
  }

  public void setExamples(List<Example> examples) {
    this.examples = examples;
  }

  public Schema examples(List<Example> examples) {
    this.examples = examples;
    return this;
  }

  public Schema addExamplesItem(Example examplesItem) {
    if(this.examples == null) {
      this.examples = new ArrayList<Example>();
    }
    this.examples.add(examplesItem);
    return this;
  }

  /**
   * returns the example property from a Schema instance.
   *
   * @return Example example
   **/
  @ApiModelProperty(value = "")
  public Example getExample() {
    return example;
  }

  public void setExample(Example example) {
    this.example = example;
  }

  public Schema example(Example example) {
    this.example = example;
    return this;
  }

  /**
   * returns the externalDocs property from a Schema instance.
   *
   * @return ExternalDocumentation externalDocs
   **/
  @ApiModelProperty(value = "")
  public ExternalDocumentation getExternalDocs() {
    return externalDocs;
  }

  public void setExternalDocs(ExternalDocumentation externalDocs) {
    this.externalDocs = externalDocs;
  }

  public Schema externalDocs(ExternalDocumentation externalDocs) {
    this.externalDocs = externalDocs;
    return this;
  }

  /**
   * returns the deprecated property from a Schema instance.
   *
   * @return Boolean deprecated
   **/
  @ApiModelProperty(value = "")
  public Boolean getDeprecated() {
    return deprecated;
  }

  public void setDeprecated(Boolean deprecated) {
    this.deprecated = deprecated;
  }

  public Schema deprecated(Boolean deprecated) {
    this.deprecated = deprecated;
    return this;
  }

  /**
   * returns the xml property from a Schema instance.
   *
   * @return XML xml
   **/
  @ApiModelProperty(value = "")
  public XML getXml() {
    return xml;
  }

  public void setXml(XML xml) {
    this.xml = xml;
  }

  public Schema xml(XML xml) {
    this.xml = xml;
    return this;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Schema schema = (Schema) o;
    return Objects.equals(this.title, schema.title) &&
        Objects.equals(this.multipleOf, schema.multipleOf) &&
        Objects.equals(this.maximum, schema.maximum) &&
        Objects.equals(this.exclusiveMaximum, schema.exclusiveMaximum) &&
        Objects.equals(this.minimum, schema.minimum) &&
        Objects.equals(this.exclusiveMinimum, schema.exclusiveMinimum) &&
        Objects.equals(this.maxLength, schema.maxLength) &&
        Objects.equals(this.minLength, schema.minLength) &&
        Objects.equals(this.pattern, schema.pattern) &&
        Objects.equals(this.maxItems, schema.maxItems) &&
        Objects.equals(this.minItems, schema.minItems) &&
        Objects.equals(this.uniqueItems, schema.uniqueItems) &&
        Objects.equals(this.maxProperties, schema.maxProperties) &&
        Objects.equals(this.minProperties, schema.minProperties) &&
        Objects.equals(this.required, schema.required) &&
        Objects.equals(this._enum, schema._enum) &&
        Objects.equals(this.type, schema.type) &&
        Objects.equals(this.not, schema.not) &&
        Objects.equals(this.properties, schema.properties) &&
        Objects.equals(this.additionalProperties, schema.additionalProperties) &&
        Objects.equals(this.description, schema.description) &&
        Objects.equals(this.format, schema.format) &&
        Objects.equals(this.ref, schema.ref) &&
        Objects.equals(this.nulable, schema.nulable) &&
        Objects.equals(this.readOnly, schema.readOnly) &&
        Objects.equals(this.writeOnly, schema.writeOnly) &&
        Objects.equals(this.examples, schema.examples) &&
        Objects.equals(this.example, schema.example) &&
        Objects.equals(this.externalDocs, schema.externalDocs) &&
        Objects.equals(this.deprecated, schema.deprecated) &&
        Objects.equals(this.xml, schema.xml);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, multipleOf, maximum, exclusiveMaximum, minimum, exclusiveMinimum, maxLength, minLength, pattern, maxItems, minItems, uniqueItems, maxProperties, minProperties, required, _enum, type, not, properties, additionalProperties, description, format, ref, nulable, readOnly, writeOnly, examples, example, externalDocs, deprecated, xml);
  }


  public java.util.Map<String, Object> getExtensions() {
    return extensions;
  }

  public void addExtension(String name, Object value) {
    if(this.extensions == null) {
      this.extensions = new java.util.HashMap<>();
    }
    this.extensions.put(name, value);
  }

  public void setExtensions(java.util.Map<String, Object> extensions) {
    this.extensions = extensions;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Schema {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    multipleOf: ").append(toIndentedString(multipleOf)).append("\n");
    sb.append("    maximum: ").append(toIndentedString(maximum)).append("\n");
    sb.append("    exclusiveMaximum: ").append(toIndentedString(exclusiveMaximum)).append("\n");
    sb.append("    minimum: ").append(toIndentedString(minimum)).append("\n");
    sb.append("    exclusiveMinimum: ").append(toIndentedString(exclusiveMinimum)).append("\n");
    sb.append("    maxLength: ").append(toIndentedString(maxLength)).append("\n");
    sb.append("    minLength: ").append(toIndentedString(minLength)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    maxItems: ").append(toIndentedString(maxItems)).append("\n");
    sb.append("    minItems: ").append(toIndentedString(minItems)).append("\n");
    sb.append("    uniqueItems: ").append(toIndentedString(uniqueItems)).append("\n");
    sb.append("    maxProperties: ").append(toIndentedString(maxProperties)).append("\n");
    sb.append("    minProperties: ").append(toIndentedString(minProperties)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    _enum: ").append(toIndentedString(_enum)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    not: ").append(toIndentedString(not)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    nulable: ").append(toIndentedString(nulable)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    writeOnly: ").append(toIndentedString(writeOnly)).append("\n");
    sb.append("    examples: ").append(toIndentedString(examples)).append("\n");
    sb.append("    example: ").append(toIndentedString(example)).append("\n");
    sb.append("    externalDocs: ").append(toIndentedString(externalDocs)).append("\n");
    sb.append("    deprecated: ").append(toIndentedString(deprecated)).append("\n");
    sb.append("    xml: ").append(toIndentedString(xml)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

