package io.swagger.v3.core;

import aQute.bnd.header.Parameters;
import aQute.bnd.osgi.Analyzer;
import aQute.bnd.osgi.Descriptors.PackageRef;
import org.testng.annotations.Test;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Set;
import java.util.TreeSet;

import static org.testng.Assert.assertTrue;

/**
 * Hardens the OSGi bundle manifest generated by {@code biz.aQute.bnd:bnd-maven-plugin} for this module.
 *
 * <p>{@code bnd-process} runs in the {@code process-classes} phase, i.e. before the tests, so
 * {@code target/classes/META-INF/MANIFEST.MF} holds the generated bundle manifest when this test runs.
 *
 * <p>Instead of hand-rolling a manifest parser, this test uses bnd's own libraries:
 * <ul>
 *   <li>{@link Analyzer} recomputes, from the module's own bytecode, the set of packages it actually
 *       references ({@code getReferred()}) minus the packages it contains itself.</li>
 *   <li>{@link Parameters} robustly parses the {@code Import-Package} header, correctly handling commas
 *       inside quoted version ranges.</li>
 * </ul>
 *
 * <p>Every externally-referenced package must be present in {@code Import-Package}. This guards against
 * regressions such as issue #156, where a bnd instruction parsing bug collapsed the header to a single
 * clause and made the bundle unusable in OSGi because referenced packages were never wired.
 */
public class OsgiManifestTest {

    private static final String MANIFEST_REL = "target/classes/META-INF/MANIFEST.MF";
    private static final String CLASSES_REL = "target/classes";

    @Test
    public void importPackageDeclaresEveryExternallyReferencedPackage() throws Exception {
        File basedir = resolveBasedir();
        Analyzer analyzer = new Analyzer();
        try {
            analyzer.setJar(new File(basedir, CLASSES_REL));
            analyzer.analyze();

            Set<String> contained = packageNames(analyzer.getContained());
            Set<String> referred = packageNames(analyzer.getReferred());

            Set<String> imported = parseImportPackages(new File(basedir, MANIFEST_REL));

            // Packages the module's bytecode uses but does not itself contain, excluding the JDK itself.
            Set<String> required = new TreeSet<>();
            for (String pkg : referred) {
                if (contained.contains(pkg) || isJdkPackage(pkg)) {
                    continue;
                }
                required.add(pkg);
            }

            Set<String> missing = new TreeSet<>(required);
            missing.removeAll(imported);
            assertTrue(missing.isEmpty(),
                    "Import-Package misses packages referenced by the module's bytecode: " + missing);

            if (required.isEmpty()) {
                throw new IllegalStateException("Test could not determine referenced packages; "
                        + "bnd Analyzer returned none for " + new File(basedir, CLASSES_REL));
            }
        } finally {
            analyzer.close();
        }
    }

    /** Resolves the module's {@code basedir}, honoring the {@code basedir} system property set by surefire. */
    private static File resolveBasedir() {
        String basedir = System.getProperty("basedir");
        File dir = basedir != null ? new File(basedir) : new File("").getAbsoluteFile();
        if (!new File(dir, MANIFEST_REL).isFile()) {
            throw new IllegalStateException(
                    "Bundle manifest not found at " + new File(dir, MANIFEST_REL).getAbsolutePath()
                            + ". bnd-process (process-classes phase) must run before the tests.");
        }
        return dir;
    }

    private static Set<String> packageNames(aQute.bnd.osgi.Packages packages) {
        Set<String> names = new TreeSet<>();
        for (PackageRef ref : packages.keySet()) {
            names.add(ref.getFQN());
        }
        return names;
    }

    private static Set<String> parseImportPackages(File manifest) {
        String header = unfold(read(manifest))
                .lines()
                .filter(l -> l.startsWith("Import-Package:"))
                .findFirst()
                .orElseThrow(() -> new IllegalStateException(manifest + " has no Import-Package header"));
        String value = header.substring("Import-Package:".length()).trim();
        return new TreeSet<>(new Parameters(value).keySet());
    }

    private static boolean isJdkPackage(String pkg) {
        return pkg.equals("java") || pkg.startsWith("java.") || pkg.startsWith("javax.") || pkg.startsWith("jdk.");
    }

    /** Joins 72-column continuation lines (a physical line starting with a space continues the previous header). */
    private static String unfold(String raw) {
        StringBuilder sb = new StringBuilder();
        for (String line : raw.split("\r?\n")) {
            if (line.startsWith(" ")) {
                sb.append(line.substring(1));
            } else {
                sb.append('\n').append(line);
            }
        }
        return sb.substring(1);
    }

    private static String read(File file) {
        try {
            return new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}