#!/bin/bash

CUR=$(pwd)
TMPDIR="$(dirname -- "${0}")"

# Javadoc is generated by mvn javadoc:javadoc into target/reports/apidocs
cp -aR "$CUR/modules/swagger-annotations/target/reports/apidocs" "$TMPDIR/apidocs"

# Copy publish script for later checkout
cp -a "$CUR/CI/publish-javadocs.sh" "$TMPDIR/publish-javadocs.sh"