name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 25 ]

    steps:
      - uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Cache local Maven repository
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Gradle packages
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Check swagger-bom version matches root version
        uses: ./.github/actions/check-bom-version

      - name: Build with Maven and Gradle
        run: |
          ./mvnw --no-transfer-progress -B install --file pom.xml
          cd ./modules/swagger-gradle-plugin
          ./gradlew build --info
          cd ../..

      - name: Deploy SNAPSHOT to Maven Central (only on push to master with Java 17)
        if: github.event_name == 'push' && matrix.java == 17
        run: |
          MY_POM_VERSION=$(./mvnw -q -DforceStdout help:evaluate -Dexpression=project.version --non-recursive)
          echo "POM VERSION: $MY_POM_VERSION"
          if [[ $MY_POM_VERSION =~ ^.*SNAPSHOT$ ]]; then
            ./mvnw --no-transfer-progress -B clean deploy -e
          else
            echo "Not a SNAPSHOT version, skipping deployment."
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

      - name: Verify BOM integration test
        run: ./mvnw --no-transfer-progress -B validate -Pbom-it